services:
  grafana:
    image: grafana/grafana:12.0.0
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3001:3000"
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro

  prometheus:
    image: prom/prometheus:v3.4.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  tempo:
    image: grafana/tempo:2.8.0
    command: ["-config.file=/etc/tempo.yml"]
    ports:
      - "3200:3200"
      - "4318:4318"
    volumes:
      - ./observability/tempo/tempo.yml:/etc/tempo.yml:ro

  loki:
    image: grafana/loki:3.5.0
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki/loki.yml:/etc/loki/local-config.yaml:ro

  alloy:
    image: grafana/alloy:v1.8.3
    command:
      - "run"
      - "/etc/alloy/config.alloy"
    ports:
      - "12345:12345"
    volumes:
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy:ro
