apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: modular-backend-lab
resources:
  - namespace.yaml
  - secrets.example.yaml
  - postgres.yaml
  - valkey.yaml
  - observability.yaml
  - ../base
images:
  - name: modular-backend-lab
    newName: modular-backend-lab
    newTag: local
