apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app.kubernetes.io/name: modular-backend-lab
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: modular-backend-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: modular-backend-lab
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modular-backend-lab
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/part-of: modular-backend-lab
    spec:
      containers:
        - name: scheduler
          image: modular-backend-lab:local
          imagePullPolicy: IfNotPresent
          command:
            - node
            - dist/workers/scheduler-app.js
          envFrom:
            - configMapRef:
                name: modular-backend-lab-config
            - secretRef:
                name: modular-backend-lab-secrets
          env:
            - name: OTEL_SERVICE_NAME
              value: modular-backend-lab-scheduler
